### your site title here

title: Bethany Chamberlain
description: PhD Fellow, Lecturer, Cat-wrangler

baseurl: ""
url: "https://www.bethany.dk"
email: "info@bethany.dk"

# Pagination
paginate: 4
permalink: /logs/:year/:title/
paginate_path: /logs/page:num/

# Social media links in footer
twitter: "chamberlain_ba"
linkedin: "bethanyannc/"
stackoverflow:
github: "bethanychamberlain"
researchgate:
orcid: "0000-0001-9184-0248"
quora:
instagram:
facebook:
mastodon: "scicomm.xyz/@bethany"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: false
    permalink: /projects/:name/
    order:
      - project1.md
      - project2.md
      - project3.md
      - project4.md
      - project5.md
      - project6.md
  teaching:
    output: true
    permalink: /teaching/:name/
    order:
      - learning-teaching.md
      - public-mental-health.md
      - data-wild.md
      - psychology-games.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
